import type { Product, Review } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Royal Bridal Clutch - Gold Embroidery",
    slug: "royal-bridal-clutch-gold",
    description:
      "Exquisite handcrafted bridal clutch featuring intricate gold embroidery and pearl embellishments. Perfect for your special day.",
    price: 4500,
    originalPrice: 6000,
    category: "bridal-clutches",
    images: ["/luxury-gold-embroidered-bridal-clutch.jpg", "/gold-bridal-clutch-detail.jpg", "/bridal-clutch-interior.jpg"],
    inStock: true,
    stockQuantity: 15,
    featured: true,
    trending: true,
    specifications: {
      Material: "Premium Silk with Gold Thread",
      Dimensions: '8" x 5" x 2"',
      Closure: "Magnetic Snap",
      Interior: "Satin Lined with Card Slots",
    },
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "2",
    name: "Pearl Elegance Bridal Clutch",
    slug: "pearl-elegance-bridal-clutch",
    description: "Stunning pearl-adorned clutch with delicate beadwork. A timeless piece for the modern bride.",
    price: 3800,
    category: "bridal-clutches",
    images: ["/pearl-bridal-clutch-elegant.jpg", "/pearl-clutch-beadwork.jpg"],
    inStock: true,
    stockQuantity: 20,
    featured: true,
    trending: false,
    specifications: {
      Material: "Velvet with Pearl Embellishments",
      Dimensions: '7.5" x 4.5" x 2"',
      Closure: "Chain Strap Included",
      Interior: "Mirror and Card Slots",
    },
    createdAt: "2025-01-20T10:00:00Z",
  },
  {
    id: "3",
    name: "Crystal Rose Bridal Clutch",
    slug: "crystal-rose-bridal-clutch",
    description:
      "Luxurious clutch adorned with Swarovski crystals in a rose pattern. Make a statement on your wedding day.",
    price: 5200,
    originalPrice: 7000,
    category: "bridal-clutches",
    images: ["/crystal-rose-bridal-clutch.jpg", "/swarovski-crystal-clutch.jpg"],
    inStock: true,
    stockQuantity: 8,
    featured: false,
    trending: true,
    specifications: {
      Material: "Satin with Swarovski Crystals",
      Dimensions: '8.5" x 5" x 2.5"',
      Closure: "Crystal Clasp",
      Interior: "Premium Satin Lining",
    },
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "4",
    name: "Premium Nikkah Pen Set - Gold",
    slug: "premium-nikkah-pen-gold",
    description:
      "Elegant gold-plated nikkah pen with intricate floral engravings. Comes in a beautiful presentation box.",
    price: 1200,
    category: "nikkah-pens",
    images: ["/gold-nikkah-pen-elegant.jpg", "/nikkah-pen-presentation-box.jpg"],
    inStock: true,
    stockQuantity: 50,
    featured: true,
    trending: true,
    specifications: {
      Material: "Gold-Plated Brass",
      Length: "5.5 inches",
      Ink: "Premium Black Ink",
      Packaging: "Velvet Presentation Box",
    },
    createdAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "5",
    name: "Crystal Nikkah Pen - Rose Gold",
    slug: "crystal-nikkah-pen-rose-gold",
    description: "Beautiful rose gold nikkah pen adorned with crystals. A perfect keepsake for your nikkah ceremony.",
    price: 1500,
    category: "nikkah-pens",
    images: ["/rose-gold-crystal-nikkah-pen.jpg", "/crystal-nikkah-pen-detail.jpg"],
    inStock: true,
    stockQuantity: 35,
    featured: false,
    trending: true,
    specifications: {
      Material: "Rose Gold with Crystal Accents",
      Length: "5.5 inches",
      Ink: "Premium Black Ink",
      Packaging: "Luxury Gift Box",
    },
    createdAt: "2025-01-25T10:00:00Z",
  },
  {
    id: "6",
    name: "Vintage Nikkah Glasses Set",
    slug: "vintage-nikkah-glasses",
    description:
      "Handcrafted vintage-style nikkah glasses with gold rim detailing. Set of 2 glasses in premium packaging.",
    price: 2800,
    category: "nikkah-glasses",
    images: ["/vintage-gold-rim-nikkah-glasses.jpg", "/nikkah-glasses-set-packaging.jpg"],
    inStock: true,
    stockQuantity: 25,
    featured: true,
    trending: false,
    specifications: {
      Material: "Crystal Glass with Gold Rim",
      Height: "6 inches",
      Capacity: "8 oz each",
      Set: "2 Glasses with Tray",
    },
    createdAt: "2025-02-05T10:00:00Z",
  },
  {
    id: "7",
    name: "Royal Crystal Nikkah Glasses",
    slug: "royal-crystal-nikkah-glasses",
    description:
      "Luxurious crystal glasses with intricate etching and pearl accents. Perfect for your nikkah ceremony.",
    price: 3500,
    originalPrice: 4500,
    category: "nikkah-glasses",
    images: ["/royal-crystal-nikkah-glasses-pearl.jpg", "/etched-crystal-nikkah-glasses.jpg"],
    inStock: true,
    stockQuantity: 12,
    featured: false,
    trending: true,
    specifications: {
      Material: "Premium Crystal with Pearl Details",
      Height: "6.5 inches",
      Capacity: "10 oz each",
      Set: "2 Glasses with Decorative Tray",
    },
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    id: "8",
    name: "Floral Embroidered Clutch",
    slug: "floral-embroidered-clutch",
    description: "Delicate floral embroidery on premium fabric. A versatile piece for weddings and formal events.",
    price: 3200,
    category: "bridal-clutches",
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    inStock: true,
    stockQuantity: 18,
    featured: false,
    trending: false,
    specifications: {
      Material: "Silk with Thread Embroidery",
      Dimensions: '7" x 4" x 2"',
      Closure: "Magnetic with Chain",
      Interior: "Multiple Compartments",
    },
    createdAt: "2025-02-15T10:00:00Z",
  },
]

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "1",
    userId: "u1",
    userName: "Ayesha Khan",
    rating: 5,
    comment: "Absolutely stunning! The quality exceeded my expectations. Perfect for my wedding day.",
    createdAt: "2025-02-20T14:30:00Z",
  },
  {
    id: "r2",
    productId: "1",
    userId: "u2",
    userName: "Fatima Ahmed",
    rating: 5,
    comment: "Beautiful craftsmanship. The gold embroidery is exquisite. Highly recommend!",
    createdAt: "2025-02-18T10:15:00Z",
  },
  {
    id: "r3",
    productId: "4",
    userId: "u3",
    userName: "Sara Ali",
    rating: 5,
    comment: "The nikkah pen is gorgeous! Came in beautiful packaging. Will treasure it forever.",
    createdAt: "2025-02-22T16:45:00Z",
  },
  {
    id: "r4",
    productId: "2",
    userId: "u4",
    userName: "Zainab Hassan",
    rating: 4,
    comment: "Lovely clutch with beautiful pearl work. Slightly smaller than expected but still perfect.",
    createdAt: "2025-02-19T11:20:00Z",
  },
  {
    id: "r5",
    productId: "6",
    userId: "u5",
    userName: "Mariam Sheikh",
    rating: 5,
    comment: "The glasses are absolutely beautiful! The gold rim adds such elegance. Perfect for nikkah.",
    createdAt: "2025-02-21T09:30:00Z",
  },
]
